version: "3.9"
services:
  poseestimation:
    image: openpose_fastapi
    build:
          context: ./
          dockerfile: Dockerfile-gpu
    container_name: pose_api
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]